Add request promise resolver
unfold/fetch-data pull request #4
Opened 2017-03-03 10:52 UTC by simenbrekken

2017-03-07 11:29 UTC, einarlove requested changes

2017-03-07 11:29 UTC, einarlove commented on src/index.js
> +export { registerRequestPromise, resolveRequestPromises } from './resolver'
Why export registerRequestPromise? What is the use-case?

2017-03-07 11:29 UTC, einarlove commented on src/resolver.js
> +export const registerRequestPromise = createRequestPromise => {
Why not
```js
registerRequestPromise = promise => {
  if (resolving && promise) {
    promises.push(promise)
  }
}
// fetchData.js
componentWillMount() {
  registerRequestPromise(this.dispatchIfNeeded(this.props))
}
```

2017-03-08 19:48 UTC, simenbrekken commented on src/index.js
> +export { registerRequestPromise, resolveRequestPromises } from './resolver'
Agreed, removed in f1b52fd

2017-03-08 19:50 UTC, simenbrekken commented on src/resolver.js
> +export const registerRequestPromise = createRequestPromise => {
Because the promise shouldn't be created unless we are actually resolving.still create a promise even if it shouldn't

2017-03-08 21:27 UTC, einarlove approved these changes

2017-03-09 07:41 UTC, merged